"use client";

import { useState } from "react";
import useSWR from "swr";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { useLocale } from "@/lib/locale-context";
import Link from "next/link";

import { fetcher } from "@/lib/fetcher";

export default function ReportPage() {
  const { t, stageLabel, locale } = useLocale();
  const [reportType, setReportType] = useState<"weekly" | "monthly">("weekly");

  const { data: report, isLoading } = useSWR(
    `/api/reports?type=${reportType}`,
    fetcher
  );

  const generateMarkdown = () => {
    if (!report) return;
    const d = report;
    const periodLabel = reportType === "weekly" ? t("report.weekly") : t("report.monthly");
    const startDate = new Date(d.period.start).toLocaleDateString(locale === "zh" ? "zh-CN" : "en-US");
    const endDate = new Date(d.period.end).toLocaleDateString(locale === "zh" ? "zh-CN" : "en-US");

    let md = `# ALLINAI ${periodLabel}\n\n`;
    md += `**${t("report.period")}**: ${startDate} - ${endDate}\n\n`;
    md += `---\n\n`;

    // Summary
    md += `## ${t("report.summary")}\n\n`;
    md += `| | |\n|---|---|\n`;
    md += `| ${locale === "zh" ? "总项目" : "Total Projects"} | ${d.summary.totalProjects} |\n`;
    md += `| ${locale === "zh" ? "活跃项目" : "Active Projects"} | ${d.summary.activeProjects} |\n`;
    md += `| ${locale === "zh" ? "新增项目" : "New Projects"} | ${d.summary.newProjects} |\n`;
    md += `| ${locale === "zh" ? "平均动量" : "Avg Momentum"} | ${d.summary.averageMomentum}/100 |\n`;
    md += `| ${t("report.stageChanges")} | ${d.summary.stageChanges} |\n`;
    md += `| ${t("report.completedValidations")} | ${d.summary.completedValidations} |\n`;
    md += `| ${locale === "zh" ? "记录指标" : "Metrics Recorded"} | ${d.summary.metricsRecorded} |\n`;
    md += `| ${locale === "zh" ? "添加笔记" : "Notes Added"} | ${d.summary.notesAdded} |\n\n`;

    // Highlights
    if (d.highlights.newProjects.length > 0) {
      md += `## ${t("report.newProjects")}\n\n`;
      for (const p of d.highlights.newProjects) {
        md += `- **${p.name}** (${stageLabel(p.stage)})\n`;
      }
      md += `\n`;
    }

    if (d.highlights.stageChanges.length > 0) {
      md += `## ${t("report.stageChanges")}\n\n`;
      for (const sc of d.highlights.stageChanges) {
        md += `- ${sc.from ? stageLabel(sc.from) : "—"} → ${stageLabel(sc.to)}\n`;
      }
      md += `\n`;
    }

    if (d.highlights.highMomentum.length > 0) {
      md += `## ${t("report.highlights")}\n\n`;
      for (const p of d.highlights.highMomentum) {
        md += `- **${p.name}** — ${locale === "zh" ? "动量" : "momentum"} ${Math.round(p.momentum)}\n`;
      }
      md += `\n`;
    }

    // Concerns
    if (d.concerns.staleProjects.length > 0 || d.concerns.lowMomentum.length > 0) {
      md += `## ${t("report.concerns")}\n\n`;
      for (const p of d.concerns.staleProjects) {
        md += `- **${p.name}** — ${locale === "zh" ? `在「${stageLabel(p.stage)}」停滞 ${p.daysInStage} 天` : `stale in ${stageLabel(p.stage)} for ${p.daysInStage} days`}\n`;
      }
      for (const p of d.concerns.lowMomentum) {
        md += `- **${p.name}** — ${locale === "zh" ? "动量低" : "low momentum"} (${Math.round(p.momentum)})\n`;
      }
      md += `\n`;
    }

    md += `---\n\n*${locale === "zh" ? "由 ALLINAI 自动生成" : "Auto-generated by ALLINAI"}*\n`;

    // Download
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `allinai-${reportType}-report-${new Date().toISOString().slice(0, 10)}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-full">
        <p className="text-muted-foreground">{t("common.loading")}</p>
      </div>
    );
  }

  return (
    <div className="p-6 space-y-6 max-w-4xl mx-auto">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold">{t("report.title")}</h1>
          <p className="text-sm text-muted-foreground">
            {report
              ? `${new Date(report.period.start).toLocaleDateString(locale === "zh" ? "zh-CN" : "en-US")} — ${new Date(report.period.end).toLocaleDateString(locale === "zh" ? "zh-CN" : "en-US")}`
              : ""}
          </p>
        </div>
        <div className="flex items-center gap-2">
          <div className="flex rounded-lg border overflow-hidden">
            <button
              className={`px-3 py-1.5 text-sm ${reportType === "weekly" ? "bg-primary text-primary-foreground" : "hover:bg-accent"}`}
              onClick={() => setReportType("weekly")}
            >
              {t("report.weekly")}
            </button>
            <button
              className={`px-3 py-1.5 text-sm ${reportType === "monthly" ? "bg-primary text-primary-foreground" : "hover:bg-accent"}`}
              onClick={() => setReportType("monthly")}
            >
              {t("report.monthly")}
            </button>
          </div>
          <Button variant="outline" onClick={generateMarkdown} disabled={!report}>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="mr-2">
              <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
              <polyline points="7 10 12 15 17 10" />
              <line x1="12" x2="12" y1="15" y2="3" />
            </svg>
            {t("report.export")}
          </Button>
        </div>
      </div>

      {report && (
        <>
          {/* Summary Cards */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <Card className="p-4 text-center">
              <p className="text-sm text-muted-foreground">{locale === "zh" ? "活跃项目" : "Active"}</p>
              <p className="text-3xl font-bold mt-1">{report.summary.activeProjects}</p>
            </Card>
            <Card className="p-4 text-center">
              <p className="text-sm text-muted-foreground">{locale === "zh" ? "平均动量" : "Avg Momentum"}</p>
              <p className="text-3xl font-bold mt-1">{report.summary.averageMomentum}</p>
              <Progress value={report.summary.averageMomentum} className="h-1.5 mt-2" />
            </Card>
            <Card className="p-4 text-center">
              <p className="text-sm text-muted-foreground">{t("report.newProjects")}</p>
              <p className="text-3xl font-bold mt-1">{report.summary.newProjects}</p>
            </Card>
            <Card className="p-4 text-center">
              <p className="text-sm text-muted-foreground">{t("report.stageChanges")}</p>
              <p className="text-3xl font-bold mt-1">{report.summary.stageChanges}</p>
            </Card>
          </div>

          {/* Activity stats */}
          <div className="grid grid-cols-3 gap-4">
            <Card className="p-4">
              <p className="text-sm text-muted-foreground">{t("report.completedValidations")}</p>
              <p className="text-2xl font-bold">{report.summary.completedValidations}</p>
              <p className="text-xs text-muted-foreground mt-1">
                {locale === "zh"
                  ? `共 ${report.summary.totalValidationCompleted}/${report.summary.totalValidationItems} 项`
                  : `${report.summary.totalValidationCompleted}/${report.summary.totalValidationItems} total`}
              </p>
            </Card>
            <Card className="p-4">
              <p className="text-sm text-muted-foreground">{locale === "zh" ? "记录指标" : "Metrics"}</p>
              <p className="text-2xl font-bold">{report.summary.metricsRecorded}</p>
            </Card>
            <Card className="p-4">
              <p className="text-sm text-muted-foreground">{locale === "zh" ? "添加笔记" : "Notes"}</p>
              <p className="text-2xl font-bold">{report.summary.notesAdded}</p>
            </Card>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Highlights */}
            <Card className="p-6">
              <h2 className="font-semibold mb-4">{t("report.highlights")}</h2>
              <div className="space-y-3">
                {report.highlights.highMomentum.length > 0 ? (
                  report.highlights.highMomentum.map((p: { id: string; name: string; momentum: number }) => (
                    <Link key={p.id} href={`/projects/${p.id}`} className="flex items-center gap-3 p-2 rounded-lg hover:bg-accent">
                      <span className="text-green-500">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="22 7 13.5 15.5 8.5 10.5 2 17" /><polyline points="16 7 22 7 22 13" /></svg>
                      </span>
                      <span className="text-sm flex-1 truncate">{p.name}</span>
                      <Badge variant="outline" className="text-green-600">{Math.round(p.momentum)}</Badge>
                    </Link>
                  ))
                ) : (
                  <p className="text-sm text-muted-foreground">{t("report.noData")}</p>
                )}
                {report.highlights.newProjects.length > 0 && (
                  <>
                    <p className="text-xs font-medium text-muted-foreground mt-2">{t("report.newProjects")}</p>
                    {report.highlights.newProjects.map((p: { id: string; name: string; stage: string }) => (
                      <Link key={p.id} href={`/projects/${p.id}`} className="flex items-center gap-3 p-2 rounded-lg hover:bg-accent">
                        <span className="text-blue-500">+</span>
                        <span className="text-sm flex-1 truncate">{p.name}</span>
                        <Badge variant="outline" className="text-xs">{stageLabel(p.stage)}</Badge>
                      </Link>
                    ))}
                  </>
                )}
              </div>
            </Card>

            {/* Concerns */}
            <Card className="p-6">
              <h2 className="font-semibold mb-4">{t("report.concerns")}</h2>
              <div className="space-y-3">
                {report.concerns.staleProjects.length === 0 && report.concerns.lowMomentum.length === 0 ? (
                  <div className="flex flex-col items-center justify-center py-6 text-muted-foreground">
                    <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" className="mb-2 text-green-500">
                      <path d="M20 6 9 17l-5-5" />
                    </svg>
                    <p className="text-sm">{t("dashboard.allOnTrack")}</p>
                  </div>
                ) : (
                  <>
                    {report.concerns.staleProjects.map((p: { id: string; name: string; stage: string; daysInStage: number }) => (
                      <Link key={p.id} href={`/projects/${p.id}`} className="flex items-center gap-3 p-2 rounded-lg hover:bg-accent">
                        <span className="text-orange-500">
                          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                            <path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3" />
                            <path d="M12 9v4" /><path d="M12 17h.01" />
                          </svg>
                        </span>
                        <div className="flex-1 min-w-0">
                          <p className="text-sm font-medium truncate">{p.name}</p>
                          <p className="text-xs text-muted-foreground">
                            {t("dashboard.daysInStage", { days: p.daysInStage, stage: stageLabel(p.stage) })}
                          </p>
                        </div>
                      </Link>
                    ))}
                    {report.concerns.lowMomentum.map((p: { id: string; name: string; momentum: number }) => (
                      <Link key={`low-${p.id}`} href={`/projects/${p.id}`} className="flex items-center gap-3 p-2 rounded-lg hover:bg-accent">
                        <span className="text-red-500">
                          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="22 17 13.5 8.5 8.5 13.5 2 7" /><polyline points="16 17 22 17 22 11" /></svg>
                        </span>
                        <span className="text-sm flex-1 truncate">{p.name}</span>
                        <Badge variant="outline" className="text-red-500">{Math.round(p.momentum)}</Badge>
                      </Link>
                    ))}
                  </>
                )}
              </div>
            </Card>
          </div>

          {/* Stage distribution */}
          <Card className="p-6">
            <h2 className="font-semibold mb-4">{t("dashboard.stageDistribution")}</h2>
            <div className="flex flex-wrap gap-3">
              {Object.entries(report.stageDistribution as Record<string, number>).map(([stage, count]) => (
                <div key={stage} className="flex items-center gap-2 bg-muted rounded-lg px-3 py-2">
                  <span className="text-sm">{stageLabel(stage)}</span>
                  <Badge variant="secondary">{count}</Badge>
                </div>
              ))}
            </div>
          </Card>
        </>
      )}
    </div>
  );
}
