"use client";

import { useState } from "react";
import useSWR from "swr";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useLocale } from "@/lib/locale-context";
import Link from "next/link";

import { fetcher } from "@/lib/fetcher";

export default function ReportPage() {
  const { t, stageLabel, locale } = useLocale();
  const [reportType, setReportType] = useState<"weekly" | "monthly">("weekly");

  const { data: report, isLoading } = useSWR(
    `/api/reports?type=${reportType}`,
    fetcher
  );

  const generateMarkdown = () => {
    if (!report) return;
    const d = report;
    const periodLabel = reportType === "weekly" ? t("report.weekly") : t("report.monthly");
    const startDate = new Date(d.period.start).toLocaleDateString(locale === "zh" ? "zh-CN" : "en-US");
    const endDate = new Date(d.period.end).toLocaleDateString(locale === "zh" ? "zh-CN" : "en-US");

    let md = `# ALLINAI ${periodLabel}\n\n`;
    md += `**${t("report.period")}**: ${startDate} - ${endDate}\n\n---\n\n`;

    md += `## ${t("report.summary")}\n\n`;
    md += `| | |\n|---|---|\n`;
    md += `| ${locale === "zh" ? "活跃项目" : "Active Projects"} | ${d.summary.activeProjects} |\n`;
    md += `| ${locale === "zh" ? "平均动量" : "Avg Momentum"} | ${d.summary.averageMomentum}/100 |\n`;
    md += `| ${t("report.stageChanges")} | ${d.summary.stageChanges} |\n`;
    md += `| ${t("report.completedValidations")} | ${d.summary.completedValidations} |\n\n`;

    if (d.highlights.stageChanges.length > 0) {
      md += `## ${t("report.stageChanges")}\n\n`;
      for (const sc of d.highlights.stageChanges) {
        md += `- ${sc.from ? stageLabel(sc.from) : "—"} → ${stageLabel(sc.to)}\n`;
      }
      md += `\n`;
    }

    if (d.highlights.highMomentum.length > 0) {
      md += `## ${t("report.highlights")}\n\n`;
      for (const p of d.highlights.highMomentum) {
        md += `- **${p.name}** — ${locale === "zh" ? "动量" : "momentum"} ${Math.round(p.momentum)}\n`;
      }
      md += `\n`;
    }

    if (d.concerns.staleProjects.length > 0 || d.concerns.lowMomentum.length > 0) {
      md += `## ${t("report.concerns")}\n\n`;
      for (const p of d.concerns.staleProjects) {
        md += `- **${p.name}** — ${locale === "zh" ? `停滞 ${p.daysInStage} 天` : `stale ${p.daysInStage} days`}\n`;
      }
      for (const p of d.concerns.lowMomentum) {
        md += `- **${p.name}** — ${locale === "zh" ? "动量低" : "low momentum"} (${Math.round(p.momentum)})\n`;
      }
      md += `\n`;
    }

    md += `---\n\n*${locale === "zh" ? "由 ALLINAI 自动生成" : "Auto-generated by ALLINAI"}*\n`;

    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `allinai-${reportType}-report-${new Date().toISOString().slice(0, 10)}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-full">
        <p className="text-muted-foreground">{t("common.loading")}</p>
      </div>
    );
  }

  return (
    <div className="p-6 space-y-6 max-w-3xl mx-auto">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold">{t("report.title")}</h1>
          <p className="text-sm text-muted-foreground">
            {report
              ? `${new Date(report.period.start).toLocaleDateString(locale === "zh" ? "zh-CN" : "en-US")} — ${new Date(report.period.end).toLocaleDateString(locale === "zh" ? "zh-CN" : "en-US")}`
              : ""}
          </p>
        </div>
        <div className="flex items-center gap-2">
          <div className="flex rounded-lg border overflow-hidden">
            <button
              className={`px-3 py-1.5 text-sm ${reportType === "weekly" ? "bg-primary text-primary-foreground" : "hover:bg-accent"}`}
              onClick={() => setReportType("weekly")}
            >
              {t("report.weekly")}
            </button>
            <button
              className={`px-3 py-1.5 text-sm ${reportType === "monthly" ? "bg-primary text-primary-foreground" : "hover:bg-accent"}`}
              onClick={() => setReportType("monthly")}
            >
              {t("report.monthly")}
            </button>
          </div>
          <Button onClick={generateMarkdown} disabled={!report}>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="mr-2">
              <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
              <polyline points="7 10 12 15 17 10" />
              <line x1="12" x2="12" y1="15" y2="3" />
            </svg>
            {t("report.export")}
          </Button>
        </div>
      </div>

      {report && (
        <>
          {/* Compact summary */}
          <Card className="p-5">
            <div className="grid grid-cols-4 gap-4 text-center">
              <div>
                <p className="text-2xl font-bold">{report.summary.activeProjects}</p>
                <p className="text-xs text-muted-foreground">{locale === "zh" ? "活跃" : "Active"}</p>
              </div>
              <div>
                <p className="text-2xl font-bold">{report.summary.averageMomentum}</p>
                <p className="text-xs text-muted-foreground">{locale === "zh" ? "平均动量" : "Avg Momentum"}</p>
              </div>
              <div>
                <p className="text-2xl font-bold">{report.summary.stageChanges}</p>
                <p className="text-xs text-muted-foreground">{t("report.stageChanges")}</p>
              </div>
              <div>
                <p className="text-2xl font-bold">{report.summary.completedValidations}</p>
                <p className="text-xs text-muted-foreground">{locale === "zh" ? "验证完成" : "Validated"}</p>
              </div>
            </div>
          </Card>

          {/* Concerns — only show if there are issues */}
          {(report.concerns.staleProjects.length > 0 || report.concerns.lowMomentum.length > 0) && (
            <Card className="p-5">
              <h2 className="font-semibold mb-3">{t("report.concerns")}</h2>
              <div className="space-y-2">
                {report.concerns.staleProjects.map((p: { id: string; name: string; stage: string; daysInStage: number }) => (
                  <Link key={p.id} href={`/projects/${p.id}`} className="flex items-center gap-3 p-2 rounded-lg hover:bg-accent">
                    <span className="text-orange-500 text-sm">!</span>
                    <span className="text-sm flex-1 truncate">{p.name}</span>
                    <span className="text-xs text-muted-foreground">
                      {t("dashboard.daysInStage", { days: p.daysInStage, stage: stageLabel(p.stage) })}
                    </span>
                  </Link>
                ))}
                {report.concerns.lowMomentum.map((p: { id: string; name: string; momentum: number }) => (
                  <Link key={`low-${p.id}`} href={`/projects/${p.id}`} className="flex items-center gap-3 p-2 rounded-lg hover:bg-accent">
                    <span className="text-red-500 text-sm">!</span>
                    <span className="text-sm flex-1 truncate">{p.name}</span>
                    <Badge variant="outline" className="text-red-500">{Math.round(p.momentum)}</Badge>
                  </Link>
                ))}
              </div>
            </Card>
          )}

          {/* Highlights — only show if there's something good */}
          {(report.highlights.highMomentum.length > 0 || report.highlights.stageChanges.length > 0) && (
            <Card className="p-5">
              <h2 className="font-semibold mb-3">{t("report.highlights")}</h2>
              <div className="space-y-2">
                {report.highlights.stageChanges.map((sc: { projectName: string; from: string; to: string }, i: number) => (
                  <div key={i} className="flex items-center gap-2 text-sm">
                    <span className="text-green-500">→</span>
                    <span>{sc.projectName || stageLabel(sc.to)}: {sc.from ? stageLabel(sc.from) : "—"} → {stageLabel(sc.to)}</span>
                  </div>
                ))}
                {report.highlights.highMomentum.map((p: { id: string; name: string; momentum: number }) => (
                  <Link key={p.id} href={`/projects/${p.id}`} className="flex items-center gap-2 text-sm hover:underline">
                    <span className="text-green-500">↑</span>
                    <span>{p.name}</span>
                    <Badge variant="outline" className="text-green-600 ml-auto">{Math.round(p.momentum)}</Badge>
                  </Link>
                ))}
              </div>
            </Card>
          )}
        </>
      )}
    </div>
  );
}
